/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Start
         * @description Initiate the GitHub OAuth authorization-code flow.
         */
        get: operations["github_start_api_v1_auth_github_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Callback
         * @description Complete OAuth: validate state, exchange the code server-side, and
         *     issue the session cookie. The code and token never reach logs or
         *     browser code.
         *
         *     Nothing here is a required query parameter, and that is deliberate.
         *     GitHub redirects a user who clicks "Cancel" to
         *     ``?error=access_denied&error_description=…&state=…`` with no ``code``
         *     at all. Declaring ``code`` required turns that ordinary, expected
         *     outcome into FastAPI's 422 validation error — a wall of JSON where a
         *     "sign-in was cancelled" message belongs.
         */
        get: operations["github_callback_api_v1_auth_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear the cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Tokens
         * @description The caller's own tokens. Never anybody else's, and never a value.
         */
        get: operations["list_api_tokens_api_v1_me_tokens_get"];
        put?: never;
        /**
         * Create Api Token
         * @description Mint a token and return it. This response is the only sight of it.
         *
         *     The expiry is computed here rather than accepted as a timestamp: a
         *     client sending an absolute moment would be asserting a shared clock,
         *     and the only clock that matters is the one the ``expires_at``
         *     predicate is evaluated against.
         */
        post: operations["create_api_token_api_v1_me_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Api Token
         * @description Revoke a token. Revoking one that is not yours is a 204 no-op.
         *
         *     Not a 404, on the reasoning ``tests/api/test_isolation.py`` already
         *     pins for bookmarks: answering differently for "not yours" and "never
         *     existed" would confirm a guessed id. The revocation either happened
         *     or there was nothing of yours to revoke, and from outside those look
         *     the same.
         */
        delete: operations["revoke_api_token_api_v1_me_tokens__token_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Current user and their preference profile.
         */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Delete the account and cascade preferences, bookmarks, reads, and
         *     sessions; then sign out.
         */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Preferences
         * @description Partial preference update in one transaction.
         */
        patch: operations["patch_preferences_api_v1_me_preferences_patch"];
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Enabled sources and topic metadata for the settings screen.
         */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed
         * @description Deduplicated feed ordered by publication time, newest first.
         *
         *     ``q`` narrows inside the same statement as every other filter, so it
         *     composes with them and pages stay full. Results stay in publication
         *     order rather than relevance order — see ``app.services.feed``.
         */
        get: operations["get_feed_api_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/read-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Read State
         * @description Mark an item read or unread; idempotent either way.
         */
        put: operations["put_read_state_api_v1_items__item_id__read_state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bookmarks
         * @description The current user's bookmarks, newest first.
         */
        get: operations["list_bookmarks_api_v1_bookmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Bookmark
         * @description Create a bookmark idempotently; repeats return the existing one.
         */
        put: operations["put_bookmark_api_v1_items__item_id__bookmark_put"];
        post?: never;
        /**
         * Delete Bookmark
         * @description Remove a bookmark; removing an absent bookmark is a 204 no-op.
         */
        delete: operations["delete_bookmark_api_v1_items__item_id__bookmark_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiTokenCreate */
        ApiTokenCreate: {
            /**
             * Label
             * @description What this token is for, in the owner's own words
             */
            label: string;
            /** @description read: safe methods only. full: everything. */
            scope: components["schemas"]["ApiTokenScope"];
            /**
             * Expires In Days
             * @description Optional lifetime in days; omit for a token that does not expire
             */
            expires_in_days?: number | null;
        };
        /**
         * ApiTokenCreated
         * @description The one and only response carrying a raw token.
         */
        ApiTokenCreated: {
            token: components["schemas"]["ApiTokenOut"];
            /**
             * Value
             * @description The token itself. Shown once, at creation. Only a hash is stored, so it cannot be retrieved again.
             */
            value: string;
        };
        /** ApiTokenList */
        ApiTokenList: {
            /** Tokens */
            tokens: components["schemas"]["ApiTokenOut"][];
        };
        /**
         * ApiTokenOut
         * @description A token as its owner sees it. Never carries the token.
         */
        ApiTokenOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            scope: components["schemas"]["ApiTokenScope"];
            /**
             * Display Prefix
             * @description The token's non-secret leading characters, for telling two tokens apart
             */
            display_prefix: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Used At
             * @description When this token was last presented successfully; null if never
             */
            last_used_at: string | null;
            /**
             * Expires At
             * @description When it stops working; null if it does not
             */
            expires_at: string | null;
        };
        /**
         * ApiTokenScope
         * @description What an API token may do. `read` permits safe methods only;
         *     `full` permits everything the owner's account can do.
         * @enum {string}
         */
        ApiTokenScope: "read" | "full";
        /** BookmarkOut */
        BookmarkOut: {
            item: components["schemas"]["FeedItemOut"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BookmarkPage */
        BookmarkPage: {
            /** Bookmarks */
            bookmarks: components["schemas"]["BookmarkOut"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null when exhausted
             */
            next_cursor: string | null;
        };
        /**
         * ErrorResponse
         * @description Shape of FastAPI's HTTPException body; used in OpenAPI responses.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** FeedItemOut */
        FeedItemOut: {
            /** Id */
            id: number;
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Image Url */
            image_url: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            source: components["schemas"]["FeedSourceRef"];
            /**
             * Topics
             * @description Topic slugs
             */
            topics: string[];
            /** Read */
            read: boolean;
            /** Bookmarked */
            bookmarked: boolean;
        };
        /** FeedPage */
        FeedPage: {
            /** Items */
            items: components["schemas"]["FeedItemOut"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page; null when exhausted
             */
            next_cursor: string | null;
        };
        /** FeedSourceRef */
        FeedSourceRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Icon Url */
            icon_url: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Live */
            live: boolean;
            /** Ready */
            ready: boolean;
            /** Liveness */
            liveness: {
                [key: string]: components["schemas"]["ProbeStatus"];
            };
            /** Readiness */
            readiness: {
                [key: string]: components["schemas"]["ProbeStatus"];
            };
        };
        /**
         * Layout
         * @enum {string}
         */
        Layout: "grid" | "list";
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["UserOut"];
            preferences: components["schemas"]["PreferencesOut"];
        };
        /** PreferencesOut */
        PreferencesOut: {
            theme: components["schemas"]["Theme"];
            layout: components["schemas"]["Layout"];
            /** Max Visible Cards */
            max_visible_cards: number;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /**
             * Topics
             * @description Selected topic slugs
             */
            topics: string[];
            /**
             * Sources
             * @description Enabled source slugs
             */
            sources: string[];
            /**
             * Muted Words
             * @description Words and phrases hidden from the feed, normalised and sorted
             */
            muted_words: string[];
            /**
             * Muted Tags
             * @description Topic slugs hidden from the feed, sorted
             */
            muted_tags: string[];
        };
        /**
         * PreferencesPatch
         * @description Partial update: absent fields are left untouched. An explicit
         *     empty list clears the corresponding selection.
         */
        PreferencesPatch: {
            theme?: components["schemas"]["Theme"] | null;
            layout?: components["schemas"]["Layout"] | null;
            /** Max Visible Cards */
            max_visible_cards?: number | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            /** Topics */
            topics?: string[] | null;
            /** Sources */
            sources?: string[] | null;
            /** Muted Words */
            muted_words?: string[] | null;
            /** Muted Tags */
            muted_tags?: string[] | null;
        };
        /** ProbeStatus */
        ProbeStatus: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * ReadFilter
         * @enum {string}
         */
        ReadFilter: "all" | "unread" | "read";
        /** ReadStateOut */
        ReadStateOut: {
            /** Item Id */
            item_id: number;
            /** Read */
            read: boolean;
            /** Read At */
            read_at: string | null;
        };
        /** ReadStateUpdate */
        ReadStateUpdate: {
            /** Read */
            read: boolean;
        };
        /** SourceOut */
        SourceOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Feed Url */
            feed_url: string;
            /** Website Url */
            website_url: string;
            /** Icon Url */
            icon_url: string | null;
            /** Refresh Minutes */
            refresh_minutes: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Topics
             * @description Default topic slugs for this source
             */
            topics: string[];
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /** Topics */
            topics: components["schemas"]["TopicOut"][];
        };
        /**
         * Theme
         * @enum {string}
         */
        Theme: "light" | "dark" | "system";
        /** TopicOut */
        TopicOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Github Id */
            github_id: number;
            /** Github Login */
            github_login: string;
            /** Display Name */
            display_name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Live but not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    github_start_api_v1_auth_github_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to GitHub's authorization page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many sign-in attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    github_callback_api_v1_auth_github_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
                error_description?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session created; redirect into the application. Also the response when GitHub reports a user denial, in which case the redirect carries a ?signin= outcome and no session. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State mismatch or user not allow-listed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many failed sign-in attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF validation failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_api_tokens_api_v1_me_tokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenList"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a signed-in session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_api_token_api_v1_me_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreated"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a signed-in session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_token_api_v1_me_tokens__token_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a signed-in session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_preferences_api_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_feed_api_v1_feed_get: {
        parameters: {
            query?: {
                /** @description Topic slugs to include; omit for the user's selection */
                topics?: string[] | null;
                /** @description Source slugs to include; omit for the user's selection */
                sources?: string[] | null;
                /** @description Narrow by the caller's read state; omit or 'all' for every item */
                read_state?: components["schemas"]["ReadFilter"];
                /** @description Full-text search over title and summary; omit for no narrowing */
                q?: string | null;
                /** @description Opaque cursor from a previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            /** @description Malformed cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_read_state_api_v1_items__item_id__read_state_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadStateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadStateOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown item */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookmarks_api_v1_bookmarks_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkPage"];
                };
            };
            /** @description Malformed cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_bookmark_api_v1_items__item_id__bookmark_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkOut"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown item */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bookmark_api_v1_items__item_id__bookmark_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown item */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
