"""Per-user API tokens.

``api_tokens`` is a long-lived credential a user hands to another
application. It sits beside ``sessions`` rather than inside it because
the two answer different questions — a session is a browser's, expires
by default, and is rotated on sign-in; a token is a user's, has no
mandatory expiry, and carries a scope. Folding them together would have
meant a nullable scope and a nullable expiry on the busiest table in the
authentication path, for no gain.

Both store the same thing at rest: a SHA-256 hex digest and nothing
else. ``display_prefix`` is the one non-secret fragment kept, so a user
can tell two tokens apart in a list.

Autogenerated from ``app.db.models`` and then hand-corrected for dialect
neutrality, exactly as the initial revision was: autogenerate rendered
the timestamp defaults as SQLite's ``(CURRENT_TIMESTAMP)`` literal, which
does not exist on PostgreSQL, and wrapped the index creation in
``batch_alter_table``, which is a SQLite workaround with nothing to work
around on a table being created in the same migration.

Constraint names come from the naming convention in ``app.db.models``
via ``op.f()``, so ``downgrade`` names the same index ``upgrade``
created, on both engines. Verified up and down against SQLite
(``tests/test_migrations.py``) and PostgreSQL
(``tests/postgres/test_dialect_paths.py``), empty and populated.

Revision ID: 45a4a04fec8c
Revises: 29038199b328
Create Date: 2026-09-03
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "45a4a04fec8c"
down_revision: str | Sequence[str] | None = "29038199b328"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("display_prefix", sa.String(length=32), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("read", "full", name="api_token_scope", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_api_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_index(op.f("ix_api_tokens_user_id"), "api_tokens", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_api_tokens_user_id"), table_name="api_tokens")
    op.drop_table("api_tokens")
