"""A GIN index for feed search, on PostgreSQL only.

``GET /feed?q=`` matches ``plainto_tsquery`` against a ``to_tsvector`` of
title and summary (``app.services.feed.search_predicate``). Without an
index that is a sequential scan plus a ``to_tsvector`` call per row, on
the table the p95 target is measured against.

**The expression here and the one in the query must match character for
character**, or PostgreSQL builds the index, reports success, and never
uses it — a guard that cannot fail, which this repository has shipped
under other names six times. So it is written once in
``app.services.feed.SEARCH_DOCUMENT_SQL`` and copied here rather than
imported: a migration that imports application code stops meaning what it
meant the day the application changes. ``tests/postgres/test_search.py``
holds the two together from the other side — it asserts the *plan*, so a
divergence shows up as a sequential scan rather than as a passing test.

``'english'`` is a literal rather than the session's ``default_text_search_config``
because ``to_tsvector(text)`` is STABLE and ``to_tsvector(regconfig, text)``
is IMMUTABLE, and only an IMMUTABLE expression can be indexed.

SQLite gets nothing. It is the development engine, its half of
``search_predicate`` is a ``LIKE`` that no index of this shape would serve,
and the corpus behind it is whatever a developer has fetched since lunch.
``op.get_bind()`` decides, so ``upgrade`` and ``downgrade`` are both
no-ops there and ``tests/test_migrations.py`` still walks the graph in
both directions.

Hand-written rather than autogenerated: ``alembic revision --autogenerate``
compares metadata to the database and this index is on neither side of
that comparison — it is an expression index the ORM does not declare,
deliberately, because declaring it in ``app/db/models.py`` would emit it
on SQLite too.

Revision ID: b7c1e0a94f6d
Revises: 45a4a04fec8c
Create Date: 2026-09-03
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b7c1e0a94f6d"
down_revision: str | Sequence[str] | None = "45a4a04fec8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

INDEX_NAME = "ix_feed_items_search"

#: Kept identical to ``app.services.feed.SEARCH_DOCUMENT_SQL``.
DOCUMENT = "feed_items.title || ' ' || coalesce(feed_items.summary, '')"


def upgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(
        f"CREATE INDEX {INDEX_NAME} ON feed_items USING GIN (to_tsvector('english', {DOCUMENT}))"
    )


def downgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(f"DROP INDEX {INDEX_NAME}")
