"""The channel artwork a feed declares about itself.

``source_status.discovered_icon_url`` holds what the last successful
parse found — RSS ``<image><url>``, or Atom ``<logo>``/``<icon>``.

On ``source_status`` and not on ``sources``, and that placement is the
whole design decision. A feed's own artwork is discovered by a fetch,
not configured by an operator. Putting it beside ``sources.icon_url``
would make the refresh loop a writer of the configuration table and
would move ``sources.updated_at`` on every poll, which are the two
properties ``source_status`` was split out to protect (see the class
docstring in ``app.db.models``). Kept apart, ``sources.icon_url`` stays
the operator's answer and takes precedence wherever both exist.

Nullable with no default and no backfill: a source that has not been
polled since this landed simply has nothing here, and the next
successful refresh fills it. Nothing reads it in a way that a null
breaks — the API coalesces to the operator's value and then to nothing,
which is what every source had before this column existed.

``String(2048)`` matches ``sources.icon_url`` and ``feed_items.image_url``
rather than being chosen afresh: it is the same kind of value from the
same kind of source, and a narrower column here would reject a URL the
neighbouring ones accept.

Autogenerated and kept, which is unusual in this history — a single
nullable column on an existing table is the one shape autogenerate emits
correctly on both engines, with no server default to render in SQLite's
dialect and no index wrapped in ``batch_alter_table``. Verified up and
down on SQLite and on PostgreSQL 18, against an empty and a populated
table.

Revision ID: e2a9c4b06d13
Revises: c3f8a17d2e40
Create Date: 2026-09-03
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e2a9c4b06d13"
down_revision: str | Sequence[str] | None = "c3f8a17d2e40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "source_status",
        sa.Column("discovered_icon_url", sa.String(length=2048), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("source_status", "discovered_icon_url")
